format = '$username$hostname$shlvl$directory$git_branch$git_commit$git_state$git_status$docker_context$terraform$aws$env_var$custom$sudo$cmd_duration$jobs$battery$time$fill$line_break$status$shell$character'

[fill]
symbol = "┅"
style = "bright-black"

[directory]
truncate_to_repo = false
truncation_length = 0
style = "bright-black"

[aws]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "bright-black"

[git_commit]
style = "bright-black"

[git_state]
style = "bright-black"

[git_status]
style = "bright-black"

[custom.criblversion]
command = 'cat .criblversion'
detect_files = ['.criblversion']
#style = 'fg:51' # something approximating a Cribl brand color
style = "bright-black"
format = '[v$output]($style) '
shell = ['bash']
